export const LOGIN_ACTION = "LOGIN";
export const LOGOUT_ACTION = "LOGOUT";
export const SIGNUP_ACTION = "SIGNUP";
export const LOGIN_SUCCESS = "LOGIN_SUCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT_ERROR = "LOGOUT_ERROR";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const PROGRESS = "PROGRESS";


export const ACTION_REPOSITORIES_LIST = "ACTION_REPOSITORIES_LIST";
export const ACTION_LIST_ERROR = "ACTION_LIST_ERROR";
export const ACTION_LIST_SUCCESS = "ACTION_LIST_SUCCESS";


export const ACTION_README = "ACTION_README";
export const ACTION_README_SUCCESS = "ACTION_README_SUCCESS";
export const ACTION_README_ERROR = "ACTION_README_ERROR";

export const PROFILE_GETUSERINFO = "PROFILE_GETUSERINFO";
export const PROFILE_GETUSERINFO_SUCCESS = "PROFILE_GETUSERINFO_SUCCESS";
export const PROFILE_GETUSERINFO_ERROR = "PROFILE_GETUSERINFO_ERROR";
export const PROFILE_UPDATEUSERINFO = "PROFILE_UPDATEUSERINFO";
export const PROFILE_UPDATEUSERINFO_SUCCESS = "PROFILE_UPDATEUSERINFO_SUCCESS";


export const ATTENDANCE_GETINFO = "ATTENDANCE_GETINFO";
export const ATTENDANCE_GETINFO_SUCCESS = "ATTENDANCE_GETINFO_SUCCESS";
export const ATTENDANCE_GETINFO_ERROR = "ATTENDANCE_GETINFO_ERROR";

export const COURSES_GETINFO = "COURSES_GETINFO";
export const COURSES_GETINFO_SUCCESS = "COURSES_GETINFO_SUCCESS";
export const COURSES_GETINFO_ERROR = "COURSES_GETINFO_ERROR";


export const ACADEMICPROGRESS_GETINFO = "ACADEMICPROGRESS_GETINFO";
export const ACADEMICPROGRESS_GETINFO_SUCCESS = "ACADEMICPROGRESS_GETINFO_SUCCESS";
export const ACADEMICPROGRESS_GETINFO_ERROR = "ACADEMICPROGRESS_GETINFO_ERROR";


export const PAYMENTS_GETINFO = "PAYMENTS_GETINFO";
export const PAYMENTS_GETINFO_SUCCESS = "PAYMENTS_GETINFO_SUCCESS";
export const PAYMENTS_GETINFO_ERROR = "PAYMENTS_GETINFO_ERROR";

export const NOTIFICATIONS_GETNOTIFICATIONS = "NOTIFICATIONS_GETNOTIFICATIONS";
export const NOTIFICATIONS_GETNOTIFICATIONS_SUCCESS = "NOTIFICATIONS_GETNOTIFICATIONS_SUCCESS";
export const NOTIFICATIONS_GETNOTIFICATIONS_ERROR = "NOTIFICATIONS_GETNOTIFICATIONS_ERROR";