import LocalizedStrings from "react-localization";

module.exports = new LocalizedStrings({
    en: {
        email: "E-mail",
        password: "Password",
        confirmpassword: "Confirm Password",
        confirmemail: 'Confirm E-mail',
        empty_error: "Cannot be empty",
        sign_in: 'Sign In',
        log_in: 'Login',
        list_title: 'Repositories',
        details: 'Details',
        tab_1: 'Tab1',
        tab_2: 'Tab2',
        tab_3: 'Tab3',
        logout: 'LogOut',
        logout_message: 'Are you sure you want to logout?',
        ok: 'Ok',
        cancel: 'Cancel',
        altsignup: "Don't have an account yet?",
        altsignin: "Do you have an account already?",
        signupnow: 'Sign Up Now!',
        register: 'Register',
        search: 'Search',
        profile: 'Profile',
        studentcard: 'Student Card',
        courses: 'Courses',
        attendance: 'Attendance',
        academicProgress: 'Academic Progress',
        payments: 'Payments',
        notifications: 'Notifications',
        personalReminders: 'Personal Reminders',
        visaExpiry: 'Visa Expiry',
        dateofbirth: 'Date of Birth',
        dateofbirth_normal: 'Date of Birth',
        cap_email: 'Email',
        address: 'Address',
        address_normal: 'Address',
        phone: 'Phone',
        phone_normal: 'Phone',
        passportnumber: 'Passport Number',
        passportnumber_normal: 'Passport Number',
        expirydate_normal: 'Expiry Date',
        issuedate_normal: 'Issue Date',
        nationality: 'Nationality',
        nationality_normal: 'Nationality',
        visatype_normal: 'Visa Type',
        editprofile: 'Edit Profile',
        fullname: 'Full Name',
        mobile_normal: 'Mobile',
        savechanges: 'Save Changes',
        sendtoemail: 'Send to E-mail',
        validate: 'Validate',
        seeallformsfromcollege: 'See All Forms From College',
        currentcourse: 'Current Course',
        pastcourse: 'PAST COURSE',
        yourattendance: 'Your Attendance',
        fullattendancereport: 'Full Attendance Report',
        emailattendancereport: 'E-mail Attendance Report',
        classcode: 'CLASS CODE',
        classdescription: 'CLASS DESCRIPTION',
        venue: 'VENUE',
        trainer: 'TRAINER',
        startdate: 'START DATE',
        starttime: 'START TIME',
        endtime: 'END TIME',
        attendance_capital: 'ATTENDANCE',
        academicprogress: 'ACADEMIC PROGRESS',
        fullacademicprogress: 'Full Academic Progress',
        emailprogressreport: 'E-mail Progress Report',
        unitCode: 'UNIT CODE',
        unitName: 'UNIT NAME',
        startdate: 'START DATE',
        enddate: 'END DATE',
        Assessment1: 'ASSESSMENT 1',
        Assessment2: 'ASSESSMENT 2',
        Assessment3: 'ASSESSMENT 3',
        outCome: 'OUTCOME',
        currentcourse: 'Current Course',
        certificate: 'Certificate',
        amount: 'Amount',
        duedate: 'Due Date',
        bankmethod: 'Bank Method',
        bankname: 'Bank Name',
        bankaccount: 'Bank Account',
        account: 'Account',
        anyfurtherquestioncontact: 'Any Further Question Contact',
        paymentsmanager: 'Payments Manager',
        banktopayments: 'Back to Payments',
        urgent: 'URGENT',
        inprogress: 'IN PROGRESS',
        done: 'DONE',
        writenewtodo: 'Write new to do',
        date: 'Date',
        seemore: 'See More',
        newsfeed: 'News Feed',
        firstName: 'First Name',
        surName: 'Surname'
    }
});