export default {
    EMAIL_REGEX: /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/,
    MIN_PASSWORD_LENGTH: 6,
    CLIENT_ID: 'ffb12e79140e7b6597ba',
    CLIENT_SECRET: 'd07dadbce095325cebfc40a46eb467e906063927',
    BASE_HEADER: {
        'Accept': 'application/vnd.github.v3.full+json',
        'Content-Type': 'application/json',
    },
    BASE_PAGE_LIMIT: 10,
    LOGIN_SCREEN: 'Login',
    SIGNUP_SCREEN: 'Signup',
    DASHBOARD_SCREEN: 'Dashboard',
    PROFILE_SCREEN: 'Profile',
    EDITPROFILE_SCREEN: 'EditProfile',
    STUDENTCARD_SCREEN: 'Studentcard',
    COURSES_SCREEN: 'Courses',
    ATTENDANCE_SCREEN: 'Attendance',
    FULLATTENDANCEREPORT_SCREEN: 'FullAttendanceReport',
    ACADEMICPROGRESS_SCREEN: 'AcademicProgress',
    FULLACADEMICPROGRESS_SCREEN: 'FullAcademicProgress',
    PAYMENTS_SCREEN: 'Payments',
    PAYMENTDETAILS_SCREEN: 'PaymentDetails',
    NOTIFICATIONS_SCREEN: 'Notifications',
    PERSONALREMINDERS_SCREEN: 'PersonalReminders',
    VISAEXPIRY_SCREEN: 'VisaExpiry',
    REPOSITORY_LIST_SCREEN: 'RepositoriesList',
    REPOSITORY_DETAILS_SCREEN: 'RepositoryDetails',
    NEWSFEED_SCREEN: 'NewsFeed',
    HARDWARE_PRESS_EVENT: 'hardwareBackPress',
}